name: LM_unlearn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=3_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - accelerate=1.7.0=pyhe01879c_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.13=py310h89163eb_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anthropic=0.56.0=pyhd8ed1ab_0
  - anyio=4.9.0=pyh29332c3_0
  - aom=3.6.1=h59595ed_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.31=he1a10d6_2
  - aws-c-cal=0.7.4=hae4d56a_2
  - aws-c-common=0.9.29=hb9d3cd8_0
  - aws-c-compression=0.2.19=h2bff981_2
  - aws-c-event-stream=0.4.3=h19b0707_4
  - aws-c-http=0.8.10=h14a7884_2
  - aws-c-io=0.14.19=hc9e6898_1
  - aws-c-mqtt=0.10.7=hb8d5873_2
  - aws-c-s3=0.6.7=h666547d_0
  - aws-c-sdkutils=0.1.19=h2bff981_4
  - aws-checksums=0.1.20=h2bff981_1
  - aws-crt-cpp=0.28.3=hbe26082_8
  - aws-sdk-cpp=1.11.407=h25d6d5c_1
  - azure-core-cpp=1.13.0=h935415a_0
  - azure-identity-cpp=1.8.0=hd126650_2
  - azure-storage-blobs-cpp=12.12.0=hd2e3451_0
  - azure-storage-common-cpp=12.7.0=h10ac4d7_1
  - azure-storage-files-datalake-cpp=12.11.0=h325d260_1
  - blas=2.132=openblas
  - blas-devel=3.9.0=32_h1ea3ea9_openblas
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py310hf71b8c6_3
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.7.15=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=py310h06a4308_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=9.10.1.4=haad7af6_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - datasets=3.6.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - dill=0.3.8=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - dm-tree=0.1.8=py310h0e2eeba_5
  - docker-pycreds=0.4.0=py_0
  - double-conversion=3.3.1=h5888daf_0
  - dp-accounting=0.5.0=pyhd8ed1ab_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - faiss=1.7.4=py310cuda112hae2f2aa_0_cuda
  - faiss-gpu=1.7.4=h788eb59_0
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py310h89163eb_0
  - freetype=2.13.3=ha770c72_1
  - frozenlist=1.6.0=py310h0a1d07c_0
  - fsspec=2025.3.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=h5eee18b_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310he8512ff_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h5888daf_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.0.0=h76408a6_0
  - hf-xet=1.1.4=py39h057ba11_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.33.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jiter=0.10.0=py310h505e2c1_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - kaldi=5.5.1112=cpu_h7360626_9
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarrow=17.0.0=had3b6fe_16_cpu
  - libarrow-acero=17.0.0=h5888daf_16_cpu
  - libarrow-dataset=17.0.0=h5888daf_16_cpu
  - libarrow-substrait=17.0.0=hf54134d_16_cpu
  - libblas=3.9.0=32_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=32_he106b2a_openblas
  - libclang-cpp20.1=20.1.7=default_h1df26ce_0
  - libclang13=20.1.7=default_he06ed0a_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=11.11.3.6=0
  - libcudnn=9.10.1.4=h7d33bf5_0
  - libcudnn-dev=9.10.1.4=h0fdc2d1_0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.5.147=0
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libfaiss=1.7.4=cuda112hb18a002_0_cuda
  - libfaiss-avx2=1.7.4=cuda112h1234567_0_cuda
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libgoogle-cloud=2.29.0=h435de7b_0
  - libgoogle-cloud-storage=2.29.0=h0121fbd_0
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblapacke=3.9.0=32_he2f377e_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm20=20.1.7=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmagma=2.8.0=h9ddd185_2
  - libmagma_sparse=2.8.0=h9ddd185_0
  - libmlir14=14.0.6=he0ac6c6_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libnvjpeg=11.9.0.86=0
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.16.1=h2387412_0
  - libopentelemetry-cpp-headers=1.16.1=ha770c72_0
  - libparquet=17.0.0=h39682fd_16_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.49=h943b412_0
  - libpq=17.5=h27ae623_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - libre2-11=2024.02.01=h2f2cdcf_0
  - libsentencepiece=0.2.0=h70df78d_3
  - libsqlite=3.50.1=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.20.0=h0e7cc3e_1
  - libtiff=4.7.0=hf01ce69_5
  - libtorch=2.4.1=cuda118_h7d43891_300
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb9d3cd8_0
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.5.0=hae8dbeb_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lit=20.1.7=pyhd8ed1ab_0
  - llvm-openmp=20.1.7=h024ca30_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h89163eb_1
  - matplotlib=3.10.3=py310hff52083_0
  - matplotlib-base=3.10.3=py310h68603db_0
  - mkl=2023.2.0=h84fe81f_50496
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.4.4=py310h89163eb_0
  - multiprocess=0.70.16=py310ha75aee5_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h3f2d84a_0
  - nltk=3.9.1=pyhd8ed1ab_1
  - numpy=1.26.4=py310hc213724_1
  - numpy-base=1.26.4=py310hf387b04_1
  - openblas=0.3.30=pthreads_h6ec200e_0
  - openfst=1.8.3=h84d6215_3
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.1=h7b32b05_0
  - optree=0.16.0=py310h3788b33_0
  - orc=2.0.2=h669347b_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py310h5eaa309_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hc749103_2
  - pillow=11.2.1=py310h7e6dc6c_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=h29eaf8c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prometheus-cpp=1.2.4=ha5d0236_1
  - propcache=0.3.1=py310h89163eb_0
  - psutil=7.0.0=py310ha75aee5_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=17.0.0=py310hb7f781d_2
  - pyarrow-core=17.0.0=py310hac404ae_2_cpu
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py310hbcd0ec0_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.0=py310hfd10a26_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-gil=3.10.18=hd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py310ha75aee5_2
  - python_abi=3.10=7_cp310
  - pytorch=2.4.1=cuda118_py310h22ea9a0_300
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h89163eb_2
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_0
  - rdma-core=54.0=h5888daf_0
  - re2=2024.02.01=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py310ha75aee5_0
  - requests=2.32.4=pyhd8ed1ab_0
  - s2n=1.5.5=h3931f03_0
  - safetensors=0.5.3=py310h505e2c1_0
  - scikit-learn=1.7.0=py310h27f47ee_1
  - scipy=1.15.2=py310h1d65ade_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sentence-transformers=5.0.0=pyhd8ed1ab_0
  - sentencepiece=0.2.0=h06a4308_3
  - sentencepiece-python=0.2.0=py310h3e0de92_3
  - sentencepiece-spm=0.2.0=h70df78d_3
  - sentry-sdk=2.30.0=pyhd8ed1ab_0
  - setproctitle=1.3.6=py310ha75aee5_0
  - setuptools=75.8.2=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h1b44611_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlite=3.32.3=hcee41ef_1
  - statsmodels=0.14.4=py310hf462985_0
  - svt-av1=1.4.1=hcb278e6_0
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.13.0=hceb3a55_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - tokenizers=0.20.4=py310hb1c6e2c_0
  - torchaudio=2.4.1=cuda_118py310h287da8d_2
  - torchvision=0.19.1=cuda118py310h34ba9ee_3
  - tornado=6.5.1=py310ha75aee5_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.46.3=pyhd8ed1ab_0
  - triton=2.0.0=cuda112py310hb224420_4
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py310ha75aee5_0
  - wandb=0.20.1=py310h505e2c1_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7f98852_2
  - yarl=1.20.1=py310h89163eb_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha75aee5_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - bert-score==0.3.13
      - bitsandbytes==0.44.1
      - immutabledict==4.2.1
      - k-means-constrained==0.7.6
      - nvidia-cusparselt-cu12==0.6.3
      - openai==2.9.0
      - ortools==9.14.6206
      - peft==0.8.2
      - protobuf==6.31.1
      - sympy==1.12
      - typing-extensions==4.14.1
      - urllib3==2.5.0
      - wrapt==1.17.2
prefix: /home/users/mz238/miniconda3/envs/LM_unlearn
